package com.example.go4lunch.goforlunch.utils;

public enum  Actions {
    ADDED,
    REMOVED,
    REMOVED_LIKED,
    UPDATE_LIKED,
    REMOVED_PICKED,
    REMOVED_PICKED_RESTAURANT,
    UPDATE_PICKED,
    UPDATE_PICKED_RESTAURANT,
    UPDATE_LIKED_RESTAURANT,
    GET_RESTAURANT_DETAIL,
    UPDATE_PHOTO,
    UPDATE_PHOTO_FIREBASE,
    UPDATE_FIREBASE_INFO_USER,
    UPDATE_USER,
    DELETE_USER,
    DELETE_FIREBASE_USER,
    SAVED,
    SAVED_FAILED,
    IS_CHOSEN,
    NOT_CHOSEN,
    TO_SAVE,
    TO_SEARCH,
    ERROR,
    EXIST
}
